version: '3.8'
services:
  mongodb:
    image: mongo:6.0.8-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db

volumes:
  data_db: